### ISSUE TITLE
Suggestion: use `console.error()` in lieu of `console.log()` for error messages in general.

### ISSUE THREAD

**Issue by paulkim26** [mismathh/TILerator#7]
Certain environments (such as git bash) can identify and take advantage of JS console errors vs. console logs.

https://github.com/mismathh/TILerator/blob/89b0711a9836d3782e2b0bdf5d0f8a20c4b0b319/src/utils.js#L44

**Comment by mismathh** [comment]
Thanks. Will do more research on how to use this effectively and will update code.
